name: time-series-adaptive-asha
debug: true
# description: 4 gpu, 8 seq length, 128 batch, 200 epoch
entrypoint:  python3 -m determined.launch.torch_distributed python3 model-offline.py
max_restarts: 0
hyperparameters:
  seq_length: 8
  batch_size: 32 #128 #64 # 16 #128
  num_layers: #2
    type: categorical
    vals: [2,4,8]
  num_heads: 2
  dim_feedforward: #10
    type: categorical
    vals: [10,1024]
  lr: 0.0001
searcher:
  name: adaptive_asha #single
  metric: "Mean Absolute Percentage Error"
  max_length:
    epochs: 100
  max_trials: 6
resources:
  slots_per_trial: 1
environment:
  image:
    cpu: determinedai/pytorch-ngc:0.34.0
