name: time-series-improve-ddp
# description: A bare-bones experiment configuration file to run the model_def.py script on a Determined cluster.
entrypoint:  python3 -m determined.launch.torch_distributed python3 model-improve-hpsearch.py
max_restarts: 0
hyperparameters:
  seq_length: 8
  batch_size: 32 #128 #64 # 16 #128
  num_layers: #2
    type: categorical
    vals: [2,4]
  num_heads: 2
  dim_feedforward: #10
    type: categorical
    vals: [10,1024]
  lr: 0.0001
searcher:
   name: single
   metric: "Mean Absolute Percentage Error"
   max_length:
     epochs: 50
resources:
  slots_per_trial: 2
environment:
  image:
    cpu: determinedai/pytorch-ngc:0.34.0
