name: time-series-improve-hp
# description: 4 gpu, 8 seq length, 128 batch, 200 epoch
entrypoint:  python3 -m determined.launch.torch_distributed python3 model-improve-hp.py
max_restarts: 0
hyperparameters:
  seq_length: 8
  batch_size: 32 #128 #64 # 16 #128
  num_layers: 2
  num_heads: 2
  dim_feedforward: 10
  lr: 0.0001
searcher:
   name: single
   metric: val_loss # single일때는 상관 없는듯
   max_length:
     epochs: 200
resources:
  slots_per_trial: 2
environment:
  image:
    cpu: determinedai/pytorch-ngc:0.34.0
