name: time-series-offline-multi-gpu
description: 4 gpus, 8 seq, 64 batch_size, 200 epochs
entrypoint:  python3 -m determined.launch.torch_distributed python3 model-offline.py
max_restarts: 0
hyperparameters:
  seq_length: 8
  batch_size: 64
  num_layers: 2
  num_heads: 2
  dim_feedforward: 10
  lr: 0.0001
searcher:
   name: single
   metric: "Mean Absolute Percentage Error"
   max_length:
     epochs: 200
resources:
  slots_per_trial: 4