name: time-series-improve-offline-2gpu
# description: A bare-bones experiment configuration file to run the model_def.py script on a Determined cluster.
entrypoint:  python3 -m determined.launch.torch_distributed python3 model-offline.py
max_restarts: 0
hyperparameters:
  seq_length: 8
  batch_size: 32
  num_layers: 2
  num_heads: 2
  dim_feedforward: 10
  lr: 0.0001
searcher:
   name: single
   metric: "Mean Absolute Percentage Error"
   max_length:
     epochs: 50
resources:
  slots_per_trial: 2
environment:
  image:
    cpu: determinedai/pytorch-ngc:0.34.0
